"use client";
import React, { useState } from 'react';
import { FileText, Loader2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { jsPDF } from "jspdf";
import MetricTooltip from './MetricTooltip';

export default function FullIndexReportCard() {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    const toastId = toast.loading("Compiling Intelligence PDF...");

    try {
      // Small artificial delay for premium "synthesis" feel
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const doc = new jsPDF();
      
      // Branding
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("NEXUS INTELLIGENCE BRIEFING", 20, 30);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`DATE: ${new Date().toLocaleDateString()}`, 20, 40);
      doc.text("STATUS: CLASSIFIED - RESEARCH ARCHIVE", 20, 45);
      
      doc.line(20, 50, 190, 50);
      
      // Metrics Section
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("EXECUTIVE METRICS", 20, 65);
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("• Research Health Score: 78/100", 25, 75);
      doc.text("• Focus Retention: 84.2%", 25, 82);
      doc.text("• Sentiment Bias: Optimistic", 25, 89);
      
      // Topic Section
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("CRITICAL TOPIC CLUSTERS", 20, 105);
      
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text("The library synthesis indicates high-density activity in AI Applications,", 25, 115);
      doc.text("Quantum Computing, and Neural Syntheses. Topic gaps detected in", 25, 122);
      doc.text("Ethics and Policy (Critical counterbalance).", 25, 129);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "italic");
      doc.text("Report generated by Nexus Intelligence Engine.", 20, 280);

      doc.save(`Nexus_Intelligence_Report_${new Date().toISOString().slice(0,10)}.pdf`);

      toast.success("Intelligence briefing exported successfully.", { id: toastId });
    } catch (error) {
       console.error("PDF Generation Error:", error);
       toast.error("Critical failure during PDF compilation.", { id: toastId });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="bg-foreground text-background rounded-[3rem] p-12 flex flex-col justify-center text-center items-center shadow-3xl relative overflow-hidden group min-h-[500px]">
      <div className="absolute top-10 right-12 z-20">
        <MetricTooltip content="Exports your entire cross-video knowledge graph into a structured, editorial-grade briefing." />
      </div>
      
      <div className="absolute -top-20 -right-20 w-64 h-64 bg-white/5 rounded-full blur-[100px] group-hover:scale-150 transition-transform duration-[2000ms]"></div>
      
      {isGenerating ? (
        <Loader2 className="w-20 h-20 mb-8 animate-spin opacity-40" />
      ) : (
        <FileText className="w-20 h-20 mb-8 opacity-20 group-hover:opacity-40 transition-opacity duration-700 hover:rotate-6 transform" />
      )}
      
      <h3 className="text-4xl font-black mb-6 uppercase tracking-[0.1em] italic leading-none">Full Index <br /> Report</h3>
      <p className="text-background/40 text-[10px] font-bold max-w-xs mb-10 leading-relaxed uppercase tracking-[0.2em]">
        Generate a comprehensive editorial deep-dive of your cross-video topics and learned directives.
      </p>
      
      <button 
        onClick={handleDownload}
        disabled={isGenerating}
        className="w-full max-w-sm bg-background text-foreground px-10 py-6 rounded-2xl font-black uppercase tracking-widest text-[10px] hover:scale-105 active:scale-95 transition-all shadow-2xl relative z-10 disabled:opacity-50 disabled:cursor-not-allowed group/btn"
      >
        {isGenerating ? "Synthesizing Archive..." : "Download Intelligence Briefing"}
      </button>

      {/* Subtle indicator */}
      <div className="absolute bottom-10 left-1/2 -translate-x-1/2 flex items-center gap-2 opacity-20">
         <span className="w-1.5 h-1.5 rounded-full bg-background animate-pulse" />
         <span className="text-[8px] font-black uppercase tracking-widest">Compiler Ready</span>
      </div>
    </div>
  );
}
